In [8]:
import numpy as np

In [9]:
P = np.random.rand(5, 5)
row_sums = P.sum(axis=1)
P = P / row_sums[:, np.newaxis]

print("Матрица переходов P:")
print(P)

Матрица переходов P:
[[0.2229575  0.39977738 0.22003933 0.12998225 0.02724355]
 [0.13377031 0.14163289 0.45306508 0.02063208 0.25089965]
 [0.28023256 0.22513197 0.03844404 0.33533417 0.12085725]
 [0.24009983 0.15335604 0.29910915 0.28406954 0.02336543]
 [0.27613127 0.19544796 0.18674428 0.18344555 0.15823094]]


In [10]:
p_initial = np.random.rand(5)
p_initial = p_initial / p_initial.sum()

print("\nНачальное распределение p:")
print(p_initial)
print("Сумма вероятностей:", p_initial.sum())


Начальное распределение p:
[0.08677975 0.12655594 0.34942534 0.27973996 0.15749901]
Сумма вероятностей: 1.0


In [11]:
p_current = p_initial.copy()
for _ in range(50):
    p_current = P.T.dot(p_current)
p_50 = p_current

print("\nРаспределение после 50 шагов (p_50):")
print(p_50)


Распределение после 50 шагов (p_50):
[0.22575326 0.22843727 0.24073055 0.18985118 0.11522773]


In [12]:
eigenvalues, eigenvectors = np.linalg.eig(P.T)
idx = np.argmin(np.abs(eigenvalues - 1))
p_stationary = np.real(eigenvectors[:, idx])
p_stationary = p_stationary / p_stationary.sum()

print("\nСтационарное распределение:")
print(p_stationary)


Стационарное распределение:
[0.22575326 0.22843727 0.24073055 0.18985118 0.11522773]


In [13]:
diff = np.linalg.norm(p_50 - p_stationary)
print("\nРазница между p_50 и p_stationary:", diff)
print("Распределения равны с точностью 1e-5:", diff < 1e-5)


Разница между p_50 и p_stationary: 2.7894008272968645e-16
Распределения равны с точностью 1e-5: True
